export * from './MenPage'
export * from './WomenPage'
export * from './KidsPage'
export * from './QuizzPage'
export * from './HomePage'
export * from './TestingComponents'
export * from './CouponsPage'
export * from './Cart'